export const SET_TOKEN_INFO = 'SET_TOKEN_INFO';
export const GET_USER_DATA = 'GET_USER_DATA';
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER';

export const GET_SCREAMS = "GET_SCREAMS";

export const MODIFY_LIKE = "MODIFY_LIKE";
export const MODIFY_UNLIKE = "MODIFY_UNLIKE";

export const DELETE_SCREAM = "DELETE_SCREAM";